//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeWebApi.DataConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patrimonio
    {
        private int id;

        public Patrimonio()
        {
        }

        public Patrimonio(int id)
        {
            this.id = id;
        }

        public string Nome { get; set; }
        public int MarcaId { get; set; }
        public string Descricao { get; set; }
        public int N_Tombo { get; set; }
    
        public virtual Marca Marca { get; set; }

        internal object GetAll()
        {
            throw new NotImplementedException();
        }

        internal void Insert()
        {
            throw new NotImplementedException();
        }

        internal void Update()
        {
            throw new NotImplementedException();
        }

        internal void SaveChanges()
        {
            throw new NotImplementedException();
        }

        internal void Delete()
        {
            throw new NotImplementedException();
        }
    }
}
